### ISSUE TITLE
Build failure with 2.5.0 due to broken semver

### ISSUE THREAD

**Issue by ctron** [zip-rs/zip2#328]
**Describe the bug**

2.5.0 should be an API compatible replacement for 2.4.0 (and older).

However, switching from 2.4.0 to 2.5.0 results in the following compilation error:

```
error[E0308]: mismatched types
   --> /home/xxx/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/utoipa-swagger-ui-9.0.0/build.rs:105:49
    |
105 |                 .ok_or(ZipError::InvalidArchive("invalid path file"))?;
    |                        ------------------------ ^^^^^^^^^^^^^^^^^^^ expected `Cow<'_, str>`, found `&str`
    |                        |
    |                        arguments to this enum variant are incorrect
    |
    = note:   expected enum `Cow<'static, str>`
            found reference `&'static str`
note: tuple variant defined here
   --> /home/xxx/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zip-2.5.0/src/result.rs:23:5
    |
23  |     InvalidArchive(Cow<'static, str>),
    |     ^^^^^^^^^^^^^^
help: try wrapping the expression in `std::borrow::Cow::Borrowed`
    |
105 |                 .ok_or(ZipError::InvalidArchive(std::borrow::Cow::Borrowed("invalid path file")))?;
    |                                                 +++++++++++++++++++++++++++                   +


```

To me, it looks like a broken semver promise.

**To Reproduce**
1. compile `utoipa-swagger-ui` with zip 2.4.0
2. switch to 2.5.0 and compile again

**Expected behavior**

It should be either zip `3.0.0`, or should have a compatible API. `2.5.0` should be yanked.

**Comment by zupzup** [comment]
> there is a patch or downgrade to what versions ?? I've just changed in cargo.lock to:
> 
> ```
> [[package]]
> name = "zip"
> version = "2.4.0"
> ```
> 
> but i get error: checksum for `zip v2.4.0` changed between lock files how to manually update cargo.lock to downgrande zip version ?

Locally, if you just remove the line with the checksum, it will be recalculated and should work in the meantime.

Something like this:

```toml
[[package]]
name = "zip"
version = "2.4.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "arbitrary",
 "crc32fast",
 "crossbeam-utils",
 "displaydoc",
 "flate2",
 "indexmap 2.8.0",
 "memchr",
 "thiserror 2.0.12",
 "zopfli",
]
```

**Comment by dfaust** [comment]
> there is a patch or downgrade to what versions ??

`cargo update -p zip --precise 2.4.2`

**Comment by DenuxPlays** [comment]
Why is this version not yanked?
Everytime I do `cargo update` I have to change the version of zip manually...

**Comment by juhaku** [comment]
If nothing else it is worth to reading through the Cargo SemVer Compatibility docs found here: https://doc.rust-lang.org/cargo/reference/semver.html so that these breaking the world fires could be avoided in future.

**Comment by hiratara** [comment]
I also encountered a breaking change when upgrading from `zip` 2.2 to 2.6. In my case, the `ZipFile` struct now requires a type parameter `R: Read`, which caused compilation errors in existing code.

I noticed that this change was not mentioned in the `CHANGELOG.md`.

https://github.com/zip-rs/zip2/blob/1d42731efcad72e9f653a5ca46ed8306f4a3ca72/CHANGELOG.md?plain=1#L3-L9

As a library user, I often rely on the changelog to understand what has changed between versions and how I might need to adapt my code. It is usually the first place I look when upgrading dependencies.

Even a brief mention of breaking changes — along with migration guidance when possible — can be incredibly helpful for downstream users. I also hope that semantic versioning will continue to be followed so that users can upgrade with confidence.

Thank you for your work on maintaining this crate. I really appreciate it.

**Comment by Pr0methean** [comment]
Fixed in 3.0.0 by the version bump, and version 2.5.0 is now yanked.
