### PR TITLE
Oldpr436

### PR DESCRIPTION
**Pull request by Pr0methean**

### CODE REVIEW

**Comment by Pr0methean** [comment]
@mass10 Please sign your commits.

**Comment by mass10** [comment]
@Pr0methean Oh,

How can I sign my existing commits ?

(Or should I re-create pull request?)

**Comment by Pr0methean** [comment]
You should probably re-create the pull request once you have GPG signing configured. Squashing it into one commit may help, because IIRC some git commands will only sign the last commit in the push.

**Comment by mass10** [comment]
I am looking at ones with label #please-sign-your-commit ...

**Comment by Pr0methean** [comment]
You'll only be able to help with ones where you are, or are in contact with, the commit author.

**Comment by mass10** [comment]
Ok, I see. I will re-create a new pull request signed.

thank you!

**Comment by Pr0methean** [comment]
If your new PR fails the build_and_test checks and it doesn't seem to be your fault, let me know; I only just committed https://github.com/zip-rs/zip2/commit/b6caa1c377adc598c99dc148d706dff11b1c11a4 tonight (to reduce the risk of having one bad PR break the whole merge queue the way https://github.com/zip-rs/zip2/pull/58 did, by not being tested against enough feature configurations), and there's a risk that I may have to add *more* feature-flag permutations.

**Comment by Pr0methean** [comment]
From https://github.com/zip-rs/zip2/actions/runs/8929959279/job/24528958007?pr=46:
```
 error[E0658]: use of unstable library feature 'file_set_times'
Error:    --> src/read.rs:574:29
    |
574 |                     outfile.set_modified(t)?;
    |                             ^^^^^^^^^^^^
    |
    = note: see issue #98245 <https://github.com/rust-lang/rust/issues/98245> for more information
```
You may have to use https://crates.io/crates/rustc_version_runtime to guard this statement against the Rust versions where file_set_times is stable.

**Comment by Pr0methean** [comment]
Be especially careful around #87, since that seems especially likely to be incompatible with other PRs that come ahead of it in the merge queue. I'd especially look at https://github.com/zip-rs/zip2/commit/c2c52f2fb4c32a6b98f39d9437684da54f48cbd5 if I were you.

**Comment by Pr0methean** [comment]
@mass10 Also, your oldest 2 commits aren't signed and verified (see https://docs.github.com/authentication/managing-commit-signature-verification/about-commit-signature-verification). Once you set up signing, you may need to squash this PR's commits and open a new one, because some Git commands will only sign the latest commit in the push.

**Comment by Pr0methean** [comment]
@mass10 Is this still needed now that #82 is merged?

**Comment by Pr0methean** [comment]
`set_modified` and `set_times` were added in Rust 1.75.0, but the current MSRV is 1.70.0. Please update it in README.md, Cargo.toml and ci.yml.

**Comment by mass10** [comment]
@Pr0methean Please give me a little more time.

Appreciate your great support!

**Comment by mass10** [comment]
I have found that `ZipArchive::extract` still doesn't restore original file timestamp on new zip2. (I want extract operation should restore the original file timestamp like as unzip on UNIX/LINUX.)

I will try to create a new pull request.

So, this #46 can be closed.

**Comment by mass10** [comment]
Now I am struggling with rustup 1.7, mmm.........

**Comment by Pr0methean** [comment]
@mass10 My policies for this crate have changed: I no longer require commit signing, and I'm willing to increase the MSRV to 1.75. Are you still interested in finishing this PR?

**Comment by mass10** [comment]
@Pr0methean Oh, Yes! I think we need this PR.

**Comment by Pr0methean** [comment]
From the failing unit test, it looks like you're missing `[cfg(feature = "chrono")]` on some of the new code.

**Comment by mass10** [comment]
@Pr0methean Thank you so much! Really appreciate!
